In [1]:
import pandas as pd

In [2]:
frame1 = pd.DataFrame({'id': ['ball', 'pencil', 'pen', 'mug', 'ashtray'],
                       'price': [12.33, 11.44, 33.21, 13.23, 33.62]})
frame2 = pd.DataFrame({'id': ['pencil', 'pencil', 'ball', 'pen'],
                       'color': ['white', 'red', 'red', 'black']})

In [3]:
frame1

        id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [4]:
frame2

       id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [5]:
pd.merge(frame1, frame2)

       id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [6]:
frame1 = pd.DataFrame({'id': ['ball', 'pencil', 'pen', 'mug', 'ashtray'],
                       'color': ['white', 'red', 'red', 'black', 'green'],
                       'brand': ['OMG', 'ABC', 'ABC', 'POD', 'POD']})
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [7]:


frame2 = pd.DataFrame({'id': ['pencil', 'pencil', 'ball', 'pen'],
                       'brand': ['OMG', 'POD', 'ABC', 'POD']})
frame2

       id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [8]:
pd.merge(frame1, frame2, on='id')

       id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [9]:
pd.merge(frame1, frame2, on='brand')

      id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [10]:
frame2.columns = ['sid', 'brand']
frame2

      sid brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [11]:
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [12]:
df = pd.merge(frame1, frame2, left_on='id', right_on='sid')
del df['sid']
df

       id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

# Join types

In [13]:
frame2.columns = ['id', 'brand']
frame2

       id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [14]:
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [15]:
pd.merge(frame1, frame2, on='id')

       id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [16]:
pd.merge(frame1, frame2, on='id', how='left')

        id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [17]:
pd.merge(frame1, frame2, on='id', how='right')

       id  color brand_x brand_y
0  pencil    red     ABC     OMG
1  pencil    red     ABC     POD
2    ball  white     OMG     ABC
3     pen    red     ABC     POD

In [18]:
pd.merge(frame1, frame2, on='id', how='outer')

        id  color brand_x brand_y
0  ashtray  green     POD     NaN
1     ball  white     OMG     ABC
2      mug  black     POD     NaN
3      pen    red     ABC     POD
4   pencil    red     ABC     OMG
5   pencil    red     ABC     POD

In [19]:
pd.merge(frame1, frame2,
         on=['id', 'brand'], how='outer')

        id  color brand
0  ashtray  green   POD
1     ball    NaN   ABC
2     ball  white   OMG
3      mug  black   POD
4      pen    red   ABC
5      pen    NaN   POD
6   pencil    red   ABC
7   pencil    NaN   OMG
8   pencil    NaN   POD

# Merge by index

In [20]:
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [21]:
frame2

       id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [22]:
pd.merge(frame1, frame2, left_index=True, right_index=True)

     id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3     mug  black     POD     pen     POD

In [23]:
frame2['sid'] = [0, 1,2]
frame2

ValueError: Length of values (3) does not match length of index (4)

In [24]:
pd.merge(frame1, frame2, left_index=True, right_on='sid')

KeyError: 'sid'

# Join method

In [25]:
frame1.join(frame2)

ValueError: columns overlap but no suffix specified: Index(['id', 'brand'], dtype='object')

In [26]:
frame_renamed = frame2.rename(columns={'id': 'id2', 'brand': 'brand2'})
frame_renamed

      id2 brand2
0  pencil    OMG
1  pencil    POD
2    ball    ABC
3     pen    POD

In [27]:
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [28]:
frame1.join(frame_renamed)

        id  color brand     id2 brand2
0     ball  white   OMG  pencil    OMG
1   pencil    red   ABC  pencil    POD
2      pen    red   ABC    ball    ABC
3      mug  black   POD     pen    POD
4  ashtray  green   POD     NaN    NaN

# Concatenation

In [29]:
import numpy as np
ser1 = pd.Series(np.random.rand(4), index=[1, 2, 3, 4])
ser2 = pd.Series(np.random.rand(4), index=[5, 6, 7, 8])

In [30]:
ser1

1    0.268593
2    0.545531
3    0.346362
4    0.944663
dtype: float64

In [31]:
ser2

5    0.555564
6    0.956401
7    0.180194
8    0.310522
dtype: float64

In [32]:
pd.concat([ser1, ser2])

1    0.268593
2    0.545531
3    0.346362
4    0.944663
5    0.555564
6    0.956401
7    0.180194
8    0.310522
dtype: float64

In [33]:
pd.concat([ser1, ser2], axis=1)

          0         1
1  0.268593       NaN
2  0.545531       NaN
3  0.346362       NaN
4  0.944663       NaN
5       NaN  0.555564
6       NaN  0.956401
7       NaN  0.180194
8       NaN  0.310522

In [34]:
pd.concat([ser1, ser2], axis=1, keys=['ser1', 'ser2'])

       ser1      ser2
1  0.268593       NaN
2  0.545531       NaN
3  0.346362       NaN
4  0.944663       NaN
5       NaN  0.555564
6       NaN  0.956401
7       NaN  0.180194
8       NaN  0.310522

In [35]:
pd.concat([ser1, ser2], keys=['Hello', 'World'])

Hello  1    0.268593
       2    0.545531
       3    0.346362
       4    0.944663
World  5    0.555564
       6    0.956401
       7    0.180194
       8    0.310522
dtype: float64

In [36]:
frame1 = pd.DataFrame(np.random.rand(9).reshape(3, 3),
                      index=[1, 2, 3], columns=['A', 'B', 'C'])
frame1

          A         B         C
1  0.919385  0.950250  0.638941
2  0.845245  0.858960  0.128031
3  0.916176  0.348089  0.588072

In [37]:

frame2 = pd.DataFrame(np.random.rand(9).reshape(3, 3),
                      index=[4, 5, 6], columns=['A', 'B', 'C'])
frame2

          A         B         C
4  0.397805  0.297351  0.137123
5  0.203539  0.604345  0.035122
6  0.718257  0.199064  0.560504

In [38]:
pd.concat([frame1, frame2], axis=0)

          A         B         C
1  0.919385  0.950250  0.638941
2  0.845245  0.858960  0.128031
3  0.916176  0.348089  0.588072
4  0.397805  0.297351  0.137123
5  0.203539  0.604345  0.035122
6  0.718257  0.199064  0.560504

In [39]:
pd.concat([frame1, frame2], axis=1)

          A         B         C         A         B         C
1  0.919385  0.950250  0.638941       NaN       NaN       NaN
2  0.845245  0.858960  0.128031       NaN       NaN       NaN
3  0.916176  0.348089  0.588072       NaN       NaN       NaN
4       NaN       NaN       NaN  0.397805  0.297351  0.137123
5       NaN       NaN       NaN  0.203539  0.604345  0.035122
6       NaN       NaN       NaN  0.718257  0.199064  0.560504

# Combining

In [40]:
ser1 = pd.Series(np.random.rand(5), index=[1, 2, 3, 4, 5])
ser2 = pd.Series(np.random.rand(4), index=[2, 4, 5, 6])

In [41]:
ser1

1    0.175568
2    0.486343
3    0.562084
4    0.808686
5    0.222392
dtype: float64

In [42]:
ser2

2    0.072040
4    0.089632
5    0.139459
6    0.880776
dtype: float64

In [43]:
ser1.combine_first(ser2)

1    0.175568
2    0.486343
3    0.562084
4    0.808686
5    0.222392
6    0.880776
dtype: float64

In [44]:
ser2.combine_first(ser1)

1    0.175568
2    0.072040
3    0.562084
4    0.089632
5    0.139459
6    0.880776
dtype: float64

In [45]:
partial = ser1[:3].combine_first(ser2[:3])

In [46]:
partial

1    0.175568
2    0.486343
3    0.562084
4    0.089632
5    0.139459
dtype: float64

# Pivoting

In [47]:
frame1 = pd.DataFrame(
    np.arange(9).reshape(3, 3),
    index=['white', 'black', 'red'],
    columns=['ball', 'pen', 'pencil']
)
frame1

       ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [48]:
tab1 = frame1.stack()
tab1

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int64

In [49]:
original = tab1.unstack()
original

       ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [50]:
tab1.unstack(level=0)

        white  black  red
ball        0      3    6
pen         1      4    7
pencil      2      5    8

In [51]:
longframe = pd.DataFrame({
    'color': ['white'] * 3 + ['red'] * 3 + ['black'] * 3,
    'item': ['ball', 'pen', 'mug'] * 3,
    'value': np.random.rand(9)
})
longframe

   color  item     value
0  white  ball  0.852800
1  white   pen  0.005534
2  white   mug  0.899791
3    red  ball  0.835110
4    red   pen  0.191585
5    red   mug  0.128603
6  black  ball  0.096774
7  black   pen  0.958786
8  black   mug  0.181961

In [52]:
wideframe = longframe.pivot(index='color', columns='item')
wideframe

          value
item       ball       mug       pen
color
black  0.096774  0.181961  0.958786
red    0.835110  0.128603  0.191585
white  0.852800  0.899791  0.005534

In [53]:
wideframe2 = longframe.pivot(index='item', columns='color')
wideframe2

          value
color     black       red     white
item
ball   0.096774  0.835110  0.852800
mug    0.181961  0.128603  0.899791
pen    0.958786  0.191585  0.005534

# Removing

In [54]:
frame1 = pd.DataFrame(
    np.arange(9).reshape(3, 3),
    index=['white', 'black', 'red'],
    columns=['ball', 'pen', 'pencil']
)

frame1

       ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [56]:
del frame1['ball']

In [57]:
frame1

       pen  pencil
white    1       2
black    4       5
red      7       8

In [61]:
df_without_pen = frame1.drop('pen', axis=1)
df_without_pen

       pencil
white       2
black       5
red         8

In [63]:
df_without_pen.drop('pen', axis=1, errors='ignore')

       pencil
white       2
black       5
red         8

In [64]:
frame1

       pen  pencil
white    1       2
black    4       5
red      7       8

In [65]:
frame1.drop('pen', axis=1, inplace=True)

In [66]:
frame1

       pencil
white       2
black       5
red         8

In [67]:
frame1.drop('black', axis=0)

       pencil
white       2
red         8

In [68]:
frame1.drop(['black', 'white'])

     pencil
red       8

In [74]:
frame1.drop(frame1[frame1['pencil']==5].index, axis=0)

       pencil
white       2
red         8

In [75]:
frame1['pencil']==5

white    False
black     True
red      False
Name: pencil, dtype: bool

In [76]:
frame1[frame1['pencil']==5]

       pencil
black       5

In [77]:
frame1[frame1['pencil']==5].index

Index(['black'], dtype='object')