In [1]:
import pandas as pd

In [2]:
frame1 = pd.DataFrame({'id': ['ball', 'pencil', 'pen', 'mug', 'ashtray'],
                       'price': [12.33, 11.44, 33.21, 13.23, 33.62]})
frame2 = pd.DataFrame({'id': ['pencil', 'pencil', 'ball', 'pen'],
                       'color': ['white', 'red', 'red', 'black']})

In [3]:
frame1

        id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [4]:
frame2

       id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [5]:
pd.merge(frame1, frame2)

       id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [6]:
frame1 = pd.DataFrame({'id': ['ball', 'pencil', 'pen', 'mug', 'ashtray'],
                       'color': ['white', 'red', 'red', 'black', 'green'],
                       'brand': ['OMG', 'ABC', 'ABC', 'POD', 'POD']})
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [7]:


frame2 = pd.DataFrame({'id': ['pencil', 'pencil', 'ball', 'pen'],
                       'brand': ['OMG', 'POD', 'ABC', 'POD']})
frame2

       id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [9]:
pd.merge(frame1, frame2, on='id')

       id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [10]:
pd.merge(frame1, frame2, on='brand')

      id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [11]:
frame2.columns = ['sid', 'brand']
frame2

      sid brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [12]:
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [14]:
df = pd.merge(frame1, frame2, left_on='id', right_on='sid')
del df['sid']
df

       id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD